steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone' ,'https://github.com/Shumicorp/redis_chess-clone','--branch', '$BRANCH_NAME', '--single-branch']

- name: 'gcr.io/cloud-builders/gsutil'
  args: [ 'cp', 'gs://buck-env-test-bucket/env', './.env']
  dir: 'redis_chess-clone'

- name: 'gcr.io/$PROJECT_ID/my-node:latest'
  entrypoint: npm
  args: ['install', '--force']
  dir: 'redis_chess-clone'

- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  args: ['-c', '/opt/sonar-scanner-4.6.0.2311-linux/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$$TOKEN -Dsonar.projectKey=sonar-chess -Dsonar.organization=shumicorp -Dsonar.sources=.' ]
  secretEnv: ['TOKEN']
  dir: 'redis_chess-clone'
  entrypoint: 'bash'
  secretEnv:
    - TOKEN

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'europe-west1-docker.pkg.dev/$PROJECT_ID/my-repo/redis_chess:$REF_NAME.$SHORT_SHA',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/my-repo/redis_chess:latest',
    '.'
    ]
  dir: 'redis_chess-clone'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-repo/redis_chess:latest']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','europe-west1-docker.pkg.dev/$PROJECT_ID/my-repo/redis_chess:$REF_NAME.$SHORT_SHA']  

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment','-n','preprod','my-app','app-node=europe-west1-docker.pkg.dev/$PROJECT_ID/my-repo/redis_chess:$REF_NAME.$SHORT_SHA','--record']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/sonarqube-token/versions/latest
    env: TOKEN
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/service-account@gcp101091-mrusn.iam.gserviceaccount.com'
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON

#test