steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone' ,'https://github.com/Shumicorp/redis_chess-clone','--branch', '$BRANCH_NAME', '--single-branch']

- name: 'gcr.io/cloud-builders/gsutil'
  args: [ 'cp', 'gs://buck-env-test-bucket/env', './.env']
  dir: 'redis_chess-clone'

- name: node:16
  entrypoint: npm
  args: ['install', '--force']
  dir: 'redis_chess-clone'

- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  args:
  - '-Dsonar.host.url=https://sonarcloud.io'
  - '-Dsonar.login=$$TOKEN'
  - '-Dsonar.projectKey=sonar-chess'
  - '-Dsonar.organization=shumicorp'
  - '-Dsonar.sources=.'
  secretEnv: ['TOKEN']
  dir: 'redis_chess-clone'

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'europe-west1-docker.pkg.dev/gcp101091-mrusn/my-repo/redis_chess:$BUILD_ID',
    '-t',
    'europe-west1-docker.pkg.dev/gcp101091-mrusn/my-repo/redis_chess:latest',
    '.'
    ]
  dir: 'redis_chess-clone'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/gcp101091-mrusn/my-repo/redis_chess:latest']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','europe-west1-docker.pkg.dev/gcp101091-mrusn/my-repo/redis_chess:$BUILD_ID']  

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment','-n','preprod','my-app','app-node=europe-west1-docker.pkg.dev/gcp101091-mrusn/my-repo/redis_chess:$BUILD_ID','--record']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'

# # - name: 'gcr.io/cloud-builders/kubectl'
# #   args: ['apply', '-f', 'app-k8s.yaml']
# #   env:
# #   - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
# #   - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'

availableSecrets:
  secretManager:
  - versionName: projects/gcp101091-mrusn/secrets/sonarqube-token/versions/latest
    env: TOKEN
serviceAccount: 'projects/gcp101091-mrusn/serviceAccounts/service-account@gcp101091-mrusn.iam.gserviceaccount.com'
#serviceAccount: 'service-account@gcp101091-mrusn.iam.gserviceaccount.com'
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON
