---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: preprod-app
  namespace: preprod
spec:
  selector:
    matchLabels:
      project: preprod-app
  template:
    metadata:
      labels:
        project: preprod-app
    spec:
      containers:
        - name: app-node
          image: europe-west1-docker.pkg.dev/gcp101091-mrusn/my-repo/redis_chess:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: balanser
  labels:
    project: preprod-app
  namespace: preprod
spec:
  selector:
    project: preprod-app   # Selecting PODs with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 8080  # Port on Load Balancer
      targetPort: 8080  # Port on Pod
  type: LoadBalancer      
